name: "Upload to S3"
description: "Uploads the lambda zip to both PROD and SANDBOX S3"
inputs:
  source-file-path:
    required: true
    description: "Path to source file to be uploaded to S3"
  prod-s3-latest-path:
    required: true
    description: "S3 path for the LATEST version in PROD"
  prod-s3-versioned-path:
    required: true
    description: "S3 path for the commit SHA version in PROD"
  sandbox-s3-latest-path:
    required: true
    description: "S3 path for the LATEST version in SANDBOX"
  sandbox-s3-versioned-path:
    required: true
    description: "S3 path for the commit SHA version in SANDBOX"

runs:
  using: "composite"
  steps:
    - name: Upload to PROD S3
      run: |
        aws s3 cp ${{ inputs.source-file-path }} s3://${{ inputs.prod-s3-latest-path }}
        aws s3 cp ${{ inputs.source-file-path }} s3://${{ inputs.prod-s3-versioned-path }}
      shell: bash

    - name: Upload to SANDBOX S3
      run: |
        aws s3 cp ${{ inputs.source-file-path }} s3://${{ inputs.sandbox-s3-latest-path }}
        aws s3 cp ${{ inputs.source-file-path }} s3://${{ inputs.sandbox-s3-versioned-path }}
      shell: bash
